# Generated by Django 3.2.7 on 2021-09-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_todo', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='like_status',
            field=models.BooleanField(default=False),
        ),
    ]
