# Generated by Django 3.0.3 on 2021-09-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0003_userips'),
    ]

    operations = [
        migrations.AddField(
            model_name='userips',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
